### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by stursby** [imgix-wordpress/images-via-imgix#6] opened 2016-12-11 16:58 UTC
Hey, @wladston. I'm having issues installing this Plugin. I downloaded the .zip and uploaded it to my WordPress build but I get the following Error:

![image](https://cloud.githubusercontent.com/assets/527849/21081625/9795d038-bf90-11e6-8e6d-71dba765e737.png)

I also unzipped the .zip and placed the folder in `/wp-content/plugins/` but the plugin does not show up in the Admin screen.

I am using WordPress version 4.7

**Comment by stevenmcdonald** [comment] 2016-12-20 22:01
I'm seeing the same thing on WordPress 4.6.1

**Comment by wladston** [comment] 2016-12-21 10:17
Hi!

I believe this might have been caused by commit 4d5bd761316dcbc5b0ff25fe9ea29d2758af6e67. 

@thisislawatts contributed several interesting features and fixes, but I didn't test the plugin after his changes.

@thisislawatts, is the zip package installing ok? I think we need to revert changes made in that commit for the plugin to install normally.

**Comment by thisislawatts** [comment] 2016-12-21 10:20
Thanks for the heads up @wladston I will take a look now

**Comment by thisislawatts** [comment] 2016-12-21 10:21
@stursby Sorry if this has held you up in anyway, will investigate now.

**Comment by thisislawatts** [comment] 2016-12-21 11:24
Hey @stursby , @stevenmcdonald I've not been able to recreate this issue and have been able to install the plugin from the .zip archive.


1. Installed WordPress 4.7
1. Downloaded [latest zip](https://github.com/wladston/imgix-wordpress/archive/master.zip)  
![screenshot 2016-12-21 at 11 16 50](https://cloud.githubusercontent.com/assets/472589/21387322/05bf90f4-c76f-11e6-921f-ac3e851bb629.png)
2. Renamed archive to `imgix_plugin.zip`
3. Uploaded to WordPress via *Upload Plugin* functionality
![screenshot 2016-12-21 at 11 22 37](https://cloud.githubusercontent.com/assets/472589/21387539/ec983788-c76f-11e6-87b6-bfbededf9cea.png)
4. Activated plugin

Would you be able to review these? Any obvious differences.

**Comment by wladston** [comment] 2016-12-21 11:27
@thisislawatts, thanks for the extensive review/testing. Let's see if the OP replies.

**Comment by stevenmcdonald** [comment] 2016-12-21 21:57
@thisislawatts I'm able to install with that latest zip

**Comment by thisislawatts** [comment] 2016-12-22 03:43
Thanks for confirming @stevenmcdonald

**Comment by thisislawatts** [comment] 2017-01-12 09:59
Fixed with [release 1.2.0](https://github.com/wladston/imgix-wordpress/releases/tag/1.2.0)

**Closed as completed by thisislawatts** 2017-01-12 09:59 UTC
